services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: factureapp-backend
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/prisma/data:/app/prisma/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: factureapp-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
