# Config temporaire HTTP uniquement (avant SSL)
server {
    listen 80;
    server_name facture.innosft.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://frontend:80;
    }
}
